### ISSUE TITLE
加入该模组后无法正常启动

### ISSUE THREAD

**Issue by beiai** [vfyjxf/topfix#2]
问题1：
目前正在玩Nomifactory的Dev版整合包，在加入topfix后，MultiMC无法正常启动，附日志文件
[logs.zip](https://github.com/vfyjxf/topfix/files/7956320/logs.zip)
在根据报错移除VanillaFix和phosphor模组后，Minecraft就可以正常打开和运行了

问题2：
Nomifactory的汉化包中加入了自定义的WrapFix-0.2-thin.jar模组
和topfix有mixin版本冲突，附日志文件
根据日志文件说明，WrapFix使用的mixin 0.8，而topfix使用的是0.7.11
[logs1.zip](https://github.com/vfyjxf/topfix/files/7956388/logs1.zip)

**Comment by vfyjxf** [comment]
尝试添加[Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility)

**Comment by vfyjxf** [comment]
> 问题1： 目前正在玩Nomifactory的Dev版整合包，在加入topfix后，MultiMC无法正常启动，附日志文件 [logs.zip](https://github.com/vfyjxf/topfix/files/7956320/logs.zip) 在根据报错移除VanillaFix和phosphor模组后，Minecraft就可以正常打开和运行了
> 
> 问题2： Nomifactory的汉化包中加入了自定义的WrapFix-0.2-thin.jar模组 和topfix有mixin版本冲突，附日志文件 根据日志文件说明，WrapFix使用的mixin 0.8，而topfix使用的是0.7.11 [logs1.zip](https://github.com/vfyjxf/topfix/files/7956388/logs1.zip)

或者你也可以尝试一下1.1版本，它更换了mixin版本

**Comment by vfyjxf** [comment]
> > 问题1： 目前正在玩Nomifactory的Dev版整合包，在加入topfix后，MultiMC无法正常启动，附日志文件 [logs.zip](https://github.com/vfyjxf/topfix/files/7956320/logs.zip) 在根据报错移除VanillaFix和phosphor模组后，Minecraft就可以正常打开和运行了
> > 问题2： Nomifactory的汉化包中加入了自定义的WrapFix-0.2-thin.jar模组 和topfix有mixin版本冲突，附日志文件 根据日志文件说明，WrapFix使用的mixin 0.8，而topfix使用的是0.7.11 [logs1.zip](https://github.com/vfyjxf/topfix/files/7956388/logs1.zip)
> 
> 或者你也可以尝试一下1.1版本，它更换了mixin版本

注意它现在依赖[MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter)

**Comment by beiai** [comment]
先说结果，我的问题解决了，不过过程有点曲折

创建一个只有top+GTCE+topfix的包：
topfix1.1 + MixinBooter3.2 报错
根据Github上MixinBooter的issues回答，切换MixinBooter版本
topfix1.1 + MixinBooter3.2.thin版本，不报错，但客户端显示没生效，还是英文
topfix1.1 + MixinBooter3.0 + Mixin 0.7-0.8，不报错，但客户端显示没生效，还是英文
topfix1.1 + MixinBooter2.0 + Mixin 0.7-0.8，不报错，但客户端显示没生效，还是英文
topfix1.0 + Mixin 0.7-0.8，不报错，客户端也生效
topfix1.0 + MixinBooter2.0，不报错，客户端也生效
...不想试了，后两种已经解决了我的问题
总的来说就是topfix1.1版本不管尝试何种组合，貌似都无法生效
